version: "2"
services:
    dbsql:
        image: mysql:5.6
        mem_limit: 2G
        cpuset: 0,1
        ports:
            - 3306:3306
        volumes:
            - ./dbsql/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
        command: --default-authentication-plugin=mysql_native_password
    msperson:
        image: node:8.10
        mem_limit: 1G
        volumes:
            - ./ms/person:/var/www/app
        environment:
            NODE_ENV: development
            DSN_HOST_READ: dbsql
            DSN_HOST_WRITE: dbsql
            DSN_USERNAME: root
            DSN_PASSWORD: root
            DSN_DBNAME: db_person
            DSN_CHARSET: "utf8"
            DSN_PORT: 3306
        working_dir: /var/www/app
        command: "npm start"
        depends_on:
            - dbsql
    msevent:
        image: node:8.10
        mem_limit: 1G
        volumes:
            - ./ms/event:/var/www/app
        environment:
            NODE_ENV: development
            DSN_HOST_READ: dbsql
            DSN_HOST_WRITE: dbsql
            DSN_USERNAME: root
            DSN_PASSWORD: root
            DSN_DBNAME: db_person
            DSN_CHARSET: "utf8"
            DSN_PORT: 3306
        working_dir: /var/www/app
        command: "npm start"
        depends_on:
            - dbsql
    msmatch:
        image: node:8.10
        mem_limit: 1G
        volumes:
            - ./ms/match:/var/www/app
        environment:
            NODE_ENV: development
            DSN_HOST_READ: dbsql
            DSN_HOST_WRITE: dbsql
            DSN_USERNAME: root
            DSN_PASSWORD: root
            DSN_DBNAME: db_person
            DSN_CHARSET: "utf8"
            DSN_PORT: 3306
        working_dir: /var/www/app
        #command: "npm start"
        depends_on:
            - dbsql
        entrypoint: /bin/bash
        tty: true
        ports:
            - 3000:3000
    web:
        image: gamemanager/web
        mem_limit: 2G
        cpuset: 0,1
        ports:
            - 80:80
        volumes:
            - ./web/server.conf:/etc/nginx/conf.d/server.conf
            - ./web/docker-entrypoint.sh:/root/docker-entrypoint.sh
            - ./web/src:/var/www/app
        build:
            dockerfile: ./web/Dockerfile
            context: .
        depends_on:
            - dbsql
            - msperson
            - msevent
            - msmatch
